### ISSUE TITLE
Platform not found

### ISSUE THREAD

**Issue by KentEkl** [vlebourl/netatmo_custom#12]
Hi,
Getting this error in the log:

Unable to prepare setup for platform netatmo.light: Platform not found (No module named 'homeassistant.components.netatmo.data_handler').
Also complaining over that "mdi:periodic-table-co2" line 47 in sensor.py should be changed to "mdi:molecule-co2"

**Comment by vlebourl** [comment]
Hi thanks for the report.
I think the first error is due to your webhook being banned on the dev app. Can you check the webhook status in https://dev.netatmo.com/apps/?
If banned, unban it then in HA developper tools, call service netatmo.unregister_webhook, then netatmo.register_webhook.

**Comment by vlebourl** [comment]
Second warning should be fixed soon.

**Comment by cgtobi** [comment]
The warning about the mdi icon should be fixed in the latest version. Just merged the changes.

**Comment by KentEkl** [comment]
Yes webhook was banned, called service netatmo.unregister_webhook, then netatmo.register_webhook but the error persists.

**Comment by cgtobi** [comment]
You did unban on dev.netatmo.com, right?

**Comment by cgtobi** [comment]
Actually that was a bug. It should be fixed now @KentEkl

**Comment by KentEkl** [comment]
Ok

**Comment by KentEkl** [comment]
No errors with the latest release.
